// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: Proto/Ginvel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义函数的参数
type HandlerInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputMethod string `protobuf:"bytes,1,opt,name=input_method,json=inputMethod,proto3" json:"input_method,omitempty"` // 方法名映射函数名
	InputData   string `protobuf:"bytes,4,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`       // 输入参数
	InputToken  string `protobuf:"bytes,5,opt,name=input_token,json=inputToken,proto3" json:"input_token,omitempty"`    // 验证参数
	InputTest   string `protobuf:"bytes,6,opt,name=input_test,json=inputTest,proto3" json:"input_test,omitempty"`       // 测试
}

func (x *HandlerInput) Reset() {
	*x = HandlerInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_Ginvel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerInput) ProtoMessage() {}

func (x *HandlerInput) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_Ginvel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerInput.ProtoReflect.Descriptor instead.
func (*HandlerInput) Descriptor() ([]byte, []int) {
	return file_Proto_Ginvel_proto_rawDescGZIP(), []int{0}
}

func (x *HandlerInput) GetInputMethod() string {
	if x != nil {
		return x.InputMethod
	}
	return ""
}

func (x *HandlerInput) GetInputData() string {
	if x != nil {
		return x.InputData
	}
	return ""
}

func (x *HandlerInput) GetInputToken() string {
	if x != nil {
		return x.InputToken
	}
	return ""
}

func (x *HandlerInput) GetInputTest() string {
	if x != nil {
		return x.InputTest
	}
	return ""
}

type HandlerBack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackState int64  `protobuf:"varint,2,opt,name=back_state,json=backState,proto3" json:"back_state,omitempty"` // 接口函数状态
	BackMsg   string `protobuf:"bytes,3,opt,name=back_msg,json=backMsg,proto3" json:"back_msg,omitempty"`        // 接口函数信息说明
	BackData  string `protobuf:"bytes,4,opt,name=back_data,json=backData,proto3" json:"back_data,omitempty"`     // 返回值
	BackToken string `protobuf:"bytes,5,opt,name=back_token,json=backToken,proto3" json:"back_token,omitempty"`  // 验证参数
	BackTest  string `protobuf:"bytes,6,opt,name=back_test,json=backTest,proto3" json:"back_test,omitempty"`     // 测试
}

func (x *HandlerBack) Reset() {
	*x = HandlerBack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_Ginvel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlerBack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerBack) ProtoMessage() {}

func (x *HandlerBack) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_Ginvel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerBack.ProtoReflect.Descriptor instead.
func (*HandlerBack) Descriptor() ([]byte, []int) {
	return file_Proto_Ginvel_proto_rawDescGZIP(), []int{1}
}

func (x *HandlerBack) GetBackState() int64 {
	if x != nil {
		return x.BackState
	}
	return 0
}

func (x *HandlerBack) GetBackMsg() string {
	if x != nil {
		return x.BackMsg
	}
	return ""
}

func (x *HandlerBack) GetBackData() string {
	if x != nil {
		return x.BackData
	}
	return ""
}

func (x *HandlerBack) GetBackToken() string {
	if x != nil {
		return x.BackToken
	}
	return ""
}

func (x *HandlerBack) GetBackTest() string {
	if x != nil {
		return x.BackTest
	}
	return ""
}

var File_Proto_Ginvel_proto protoreflect.FileDescriptor

var file_Proto_Ginvel_proto_rawDesc = []byte{
	0x0a, 0x12, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x47, 0x69, 0x6e, 0x76, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x0c,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f,
	0x0a, 0x0b, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x65, 0x73, 0x74, 0x22, 0xa0,
	0x01, 0x0a, 0x0b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x62, 0x61, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x62, 0x61, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x63, 0x6b,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x63,
	0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x63, 0x6b, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x65, 0x73,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x65, 0x73,
	0x74, 0x32, 0x43, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0b,
	0x47, 0x72, 0x70, 0x63, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x1a, 0x12, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72,
	0x42, 0x61, 0x63, 0x6b, 0x22, 0x00, 0x42, 0x3c, 0x0a, 0x14, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x67, 0x69, 0x6e, 0x76, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x0b,
	0x47, 0x69, 0x6e, 0x76, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x15, 0x67,
	0x69, 0x6e, 0x76, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x47, 0x72, 0x70, 0x63, 0x2f, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Proto_Ginvel_proto_rawDescOnce sync.Once
	file_Proto_Ginvel_proto_rawDescData = file_Proto_Ginvel_proto_rawDesc
)

func file_Proto_Ginvel_proto_rawDescGZIP() []byte {
	file_Proto_Ginvel_proto_rawDescOnce.Do(func() {
		file_Proto_Ginvel_proto_rawDescData = protoimpl.X.CompressGZIP(file_Proto_Ginvel_proto_rawDescData)
	})
	return file_Proto_Ginvel_proto_rawDescData
}

var file_Proto_Ginvel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Proto_Ginvel_proto_goTypes = []interface{}{
	(*HandlerInput)(nil), // 0: Proto.HandlerInput
	(*HandlerBack)(nil),  // 1: Proto.HandlerBack
}
var file_Proto_Ginvel_proto_depIdxs = []int32{
	0, // 0: Proto.Greeter.GrpcHandler:input_type -> Proto.HandlerInput
	1, // 1: Proto.Greeter.GrpcHandler:output_type -> Proto.HandlerBack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Proto_Ginvel_proto_init() }
func file_Proto_Ginvel_proto_init() {
	if File_Proto_Ginvel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Proto_Ginvel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlerInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_Ginvel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlerBack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Proto_Ginvel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Proto_Ginvel_proto_goTypes,
		DependencyIndexes: file_Proto_Ginvel_proto_depIdxs,
		MessageInfos:      file_Proto_Ginvel_proto_msgTypes,
	}.Build()
	File_Proto_Ginvel_proto = out.File
	file_Proto_Ginvel_proto_rawDesc = nil
	file_Proto_Ginvel_proto_goTypes = nil
	file_Proto_Ginvel_proto_depIdxs = nil
}
